### PR TITLE
Fix outstanding issues #14

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes outstanding issues on #14 & #7

### CODE REVIEW

**Comment by andytudhope** [comment]
@iamonuwa would you mind targeting `master` with this PR please, as we have switched over to using that now that all other work is complete and we are preparing for launch :rocket:

**Comment by andytudhope** [comment]
Also, you fixed #8 didn't you?

**Comment by iamonuwa** [comment]
#8 was fixed in my previous PR.

**Comment by iamonuwa** [comment]
I've rebased and resolved merge conflict with master. Currently testing the branch before pushing. I guess we can create a PR from this branch to master afterwards. Then I'll focus on working directly from master branch

**Comment by andytudhope** [comment]
@iamonuwa before I merge into `deployment` then, are you happy with the results of your tests from yesterday?

**Comment by iamonuwa** [comment]
> @iamonuwa before I merge into `deployment` then, are you happy with the results of your tests from yesterday?

Absolutely

**Pull request closed without merging**
