### PR TITLE
Wrong tooltip for Upvote / Downvote actions

### LINKED ISSUE #22: Wrong tooltip for Upvote / Downvote actions
If user upvotes/downvotes dapp -> after txn is confirmed he sees [Published] tooltip, which is confusing. Please show:

1. Upvoted when transaction for upvote is confirmed
2. Downvoted when transaction for downvote is confirmed

image

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes #22

### CODE REVIEW

**Review by andytudhope — APPROVED** [review]

**Comment by andytudhope** [comment]
Actually, hang on. Just looking at this - what will happen when the message needs to actually be `Published` when a DApp is submitted?

**Comment by iamonuwa** [comment]
The transaction is only called from the Votes component

**Comment by andytudhope** [comment]
Not true @iamonuwa: https://github.com/dap-ps/discover/blob/master/src/modules/Submit/Submit.reducer.js#L170

**Comment by iamonuwa** [comment]
> Not true @iamonuwa: https://github.com/dap-ps/discover/blob/master/src/modules/Submit/Submit.reducer.js#L170

Wow, I did a search and only Votes came up. I'll reintroduce a check where published is true and message is empty to display published

**Comment by andytudhope** [comment]
@iamonuwa please also make sure to check here: https://github.com/dap-ps/discover/blob/master/src/modules/Withdraw/Withdraw.reducer.js#L69 and ensure that we can have a `Withdrawn` message too. Lmk know how you are going here and see https://github.com/dap-ps/discover/pull/36 for a much easier local setup.

**Review by andytudhope — CHANGES_REQUESTED** [review]
Waiting for fixes for both `Published` from Submit.reducer and `Withdrawn` from Withdraw.reducer

**Comment by iamonuwa** [comment]
> Waiting for fixes for both `Published` from Submit.reducer and `Withdrawn` from Withdraw.reducer

Expect PRs today

**Pull request closed without merging**
