### PR TITLE
Add review icon

### LINKED ISSUE #63: Approved Badge for DApps that have passed review
Submitted DApps currently go through a manual review process.

1. If they stake SNT, DApps appear in the "Highest Ranked" section regardless, no review.
2. In order to appear in their chosen category, and in the rest of the site, they need to be 'approved', which means EIP-1102 compliant, privacy-protecting, and mobile-optimised so that they work within Status.

So, once approved, we need some means of showing that visually on the site. Luckily for us, we [have a design for this](https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Browser?node-id=35%3A420), so this is a bounty issue to simply implement the blue tick badge shown on that page for all DApps with the status of 'APPROVED'.

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes #63

### CODE REVIEW

**Comment by andytudhope** [comment]
Hey @iamonuwa - this looks great to me. I am having issues on Firefox with submitting though - I get through the first 2 screens, but the modal disappears as soon as I want to Begin.

I cannot replicate on Brave/Chrome. And the same issue appears to happen on dev.dap.ps

Could you take a look to see if you can replicate it? If you can, maybe we can fix it here, if it is something bigger than a UI issue, we can merge here and open a new issue for it.

**Comment by andytudhope** [comment]
Ok no, actually, this doesn't work for me locally. When I submit a new DApp and stake SNT on it, it appears immediately with the 'APPROVED' badge, even though I have not approved it.

It should not have this badge, and the badge should only appear when the status is changed - i.e. DApps can have staked SNT, appear in the 'Highest Ranked' section, and yet not have the badge. All the DApps in the categories and 'Recently Added' section will have the badge, because they must all be APPROVED to appear there. The badge will help users delineate between Status-useful, and general DApps, in the 'Highest Ranked' section in the future, when many have staked.

We can solve the Firefox submission issue in a separate task.

**Comment by iamonuwa** [comment]
Apart from status key, which other key should I look out for so that the badge will be shown?

**Comment by andytudhope** [comment]
@iamonuwa the status key should just be enough. Not sure why the badge is showing up even when the status is NEW though, that is the issue with this PR.

**Comment by andytudhope** [comment]
Perfect, thank you :heart:

**Review by andytudhope — APPROVED** [review]

**Pull request merged**
