### PR TITLE
Fix confirmation downvote issue

### LINKED ISSUE #24: Confirmation for downvote is never shown
User always see Waiting for confirmation even when txn has reach more than 12 confirmations already

image

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes #24

### CODE REVIEW

**Comment by andytudhope** [comment]
Hey @iamonuwa - I do not see how this solves the problem at all? We want to speed up how transactions are processed in the client by doing things like removing [this interval](https://github.com/dap-ps/discover/blob/master/src/modules/TransactionStatus/TransactionStatus.reducer.js#L40) in tandem with better use of the web3 package.

And everything else I outlined in [this comment](https://github.com/dap-ps/discover/issues/42#issuecomment-521937311). It's not just about adding one better line from web3.

**Comment by iamonuwa** [comment]
Alright, I'll work on this this weekend

**Comment by andytudhope** [comment]
@iamonuwa what's the story here? Have you been able to speed things up and simplify the code somewhat?

**Comment by iamonuwa** [comment]
Am doing some R&D on this issue. To thinker the best way to fix this. It will be ready by tomorrow

**Pull request merged**
