### PR TITLE
Fix metadata edits

### PR DESCRIPTION
**Pull request by bakasura980**

### CODE REVIEW

**Comment by andytudhope** [comment]
Ok @bakasura980 - thanks :heart:

1. Are you sure that you have the correct discover-abi there? 
2. How does this fix issues with the cache so that it shows only the most up-to-date metadata, but still attached to the correct DApp, with the correct `sntValue`? Is there no change required in the frontend to only show UPDATED metadata?
3. How did you test this?

**Comment by bakasura980** [comment]
Hey @andytudhope 
1.  I compiled the contracts and deployed them locally. It should be the correct abi
2. It was not a cache problem, as i thought earlier. The problem was:
When someone updates the metadata, we have a check if the old one is already approved and if so, the new one automatically becomes approved and in this moment we have both approved. On metadata fetching, we are getting the old one and that is why the DApp was with 0 ranking(not relevant anymore). I added a new status - UPDATED, and now only the new one becomes APPROVED and when fetching we are getting the new data only.
3. Run the whole project locally - Test if metadata edits works. Please do the same in order for you to be sure, that everything is fine

**Comment by andytudhope** [comment]
@bakasura980 I have tested locally. Here is what happens: the edit is successful, and it shows the DApp with the correct balance and description. The edited DApp is not approved, but set to `NEW` in the DB. Only the edited DApp appears on the site (even though the unedited one is still set to `APPROVED` - shouldn't it be `UPDATED`?). After approving, the DApp appears again in Recently Added and it's chosen category too.

Nice work! Am happy to merge this after that last question about UPDATED.

**Comment by andytudhope** [comment]
There is also an error in my local terminal when running `yarn server-start` (off this branch: https://github.com/dap-ps/discover/pull/36 ):
```
[2019-08-13 09:13:26]-[ERROR]-[Discover-Service]: Error fetching correct data from contract
(node:11311) UnhandledPromiseRejectionWarning: Error: A dapp with id [0xa2dbb41916c5f674df3df8cda11e3f41746ff4834a5b2775f6b980304f3e79f6] is not found in the contract
    at Function.retrieveDApp (/home/cryptowander/Status/discover/full-build/services/discover-service.js:26:19)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:11311) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Which I assume is because it's not finding the old `dappId` now that the metadata has changed. Could we not put the offending function inside a try catch block as suggested?

**Comment by andytudhope** [comment]
It's just a weird error that doesn't block this, tbh. That dappID does exist in the contract and is still found and displayed correctly in the app. So, if you can't reproduce it, I am happy to merge here @bakasura980

**Comment by bakasura980** [comment]
I can't reproduce it, but test it in local ganache and on ropsten and everything seems to work as expected @andytudhope

**Review by andytudhope — APPROVED** [review]

**Pull request merged**
